name: Validate and test

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

jobs:
  compile:
    name: Test and compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        SCALA_VERSION: [ 2.13, 3.3 ]
        JAVA_VERSION: [ 17, 21 ]
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Java ${{ matrix.JAVA_VERSION }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: ${{ matrix.JAVA_VERSION }}

      - name: Install sbt
        uses: sbt/setup-sbt@af116cce31c00823d3903ce687f9cda3a4f19f1b # v1.2.1

      - name: Cache Coursier cache
        uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d # v8.1.1

      - name: Enable jvm-opts
        run: cp .jvmopts-ci .jvmopts

      - name: Compile and test for JDK ${{ matrix.JAVA_VERSION }}, Scala ${{ matrix.SCALA_VERSION }}
        run: sbt ++${{ matrix.SCALA_VERSION }} test:compile

  test-postgres:
    name: Run test with Postgres
    runs-on: ubuntu-latest
    strategy:
      matrix:
        SCALA_VERSION: [ 2.13, 3.3 ]
        JAVA_VERSION: [ 17 ]
    if: github.repository == 'apache/pekko-persistence-r2dbc'
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Java ${{ matrix.JAVA_VERSION }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: ${{ matrix.JAVA_VERSION }}

      - name: Install sbt
        uses: sbt/setup-sbt@af116cce31c00823d3903ce687f9cda3a4f19f1b # v1.2.1

      - name: Cache Coursier cache
        uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d # v8.1.1

      - name: Enable jvm-opts
        run: cp .jvmopts-ci .jvmopts

      - name: Start DB
        run: |-
          docker compose -f docker/docker-compose-postgres.yml up -d --wait
          # loop to wait for the DB to be ready
          for i in {1..8}; do
            if docker exec -i docker-postgres-db-1 psql -U postgres \
                -t -c 'SELECT 1;' 2>/dev/null; then
              break
            fi
            echo "Retry $i: SQL check failed, waiting before retry..."
            sleep $((i * 2))
          done
          docker exec -i docker-postgres-db-1 psql -U postgres -t < ddl-scripts/create_tables_postgres.sql
          docker exec -i docker-postgres-db-1 psql -U postgres -t -c 'CREATE DATABASE database1;'
          docker exec -i docker-postgres-db-1 psql -U postgres -t -d database1 < ddl-scripts/create_tables_postgres.sql
          docker exec -i docker-postgres-db-1 psql -U postgres -t -c 'CREATE DATABASE database2;'
          docker exec -i docker-postgres-db-1 psql -U postgres -t -d database2 < ddl-scripts/create_tables_postgres.sql

      - name: test
        run: sbt ++${{ matrix.SCALA_VERSION }} test

  test-postgres-jsonb:
    name: Run test with Postgres (JSONB)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        SCALA_VERSION: [ 2.13, 3.3 ]
        JAVA_VERSION: [ 17 ]
    if: github.repository == 'apache/pekko-persistence-r2dbc'
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Java ${{ matrix.JAVA_VERSION }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: ${{ matrix.JAVA_VERSION }}

      - name: Install sbt
        uses: sbt/setup-sbt@af116cce31c00823d3903ce687f9cda3a4f19f1b # v1.2.1

      - name: Cache Coursier cache
        uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d # v8.1.1

      - name: Enable jvm-opts
        run: cp .jvmopts-ci .jvmopts

      - name: Start DB
        run: |-
          docker compose -f docker/docker-compose-postgres.yml up -d --wait
          # loop to wait for the DB to be ready
          for i in {1..8}; do
            if docker exec -i docker-postgres-db-1 psql -U postgres \
                -t -c 'SELECT 1;' 2>/dev/null; then
              break
            fi
            echo "Retry $i: SQL check failed, waiting before retry..."
            sleep $((i * 2))
          done
          docker exec -i docker-postgres-db-1 psql -U postgres -t < ddl-scripts/create_tables_postgres_jsonb.sql

      - name: test
        run: |-
          sbt -Dpekko.persistence.r2dbc.journal.payload-column-type=JSONB -Dpekko.persistence.r2dbc.snapshot.payload-column-type=JSONB -Dpekko.persistence.r2dbc.state.payload-column-type=JSONB "core/testOnly *persistence.r2dbc.PayloadSpec"

  test-yugabyte:
    name: Run tests with Yugabyte
    runs-on: ubuntu-latest
    strategy:
      matrix:
        SCALA_VERSION: [ 2.13, 3.3 ]
        JAVA_VERSION: [ 17 ]
    if: github.repository == 'apache/pekko-persistence-r2dbc'
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Java ${{ matrix.JAVA_VERSION }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: ${{ matrix.JAVA_VERSION }}

      - name: Install sbt
        uses: sbt/setup-sbt@af116cce31c00823d3903ce687f9cda3a4f19f1b # v1.2.1

      - name: Cache Coursier cache
        uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d # v8.1.1

      - name: Enable jvm-opts
        run: cp .jvmopts-ci .jvmopts

      - name: Start DB
        run: |-
          docker compose -f docker/docker-compose-yugabyte.yml up -d --wait
          # loop to wait for the DB to be ready
          for i in {1..8}; do
            if docker exec -i yb-tserver-n1 /home/yugabyte/bin/ysqlsh \
                -h yb-tserver-n1 -t -c 'SELECT 1;' 2>/dev/null; then
              break
            fi
            echo "Retry $i: SQL check failed, waiting before retry..."
            sleep $((i * 2))
          done
          docker exec -i yb-tserver-n1 /home/yugabyte/bin/ysqlsh -h yb-tserver-n1 -t < ddl-scripts/create_tables_yugabyte.sql
          docker exec -i yb-tserver-n1 /home/yugabyte/bin/ysqlsh -h yb-tserver-n1 -t -c 'CREATE DATABASE database1;'
          docker exec -i yb-tserver-n1 /home/yugabyte/bin/ysqlsh -h yb-tserver-n1 -t -d database1 < ddl-scripts/create_tables_yugabyte.sql
          docker exec -i yb-tserver-n1 /home/yugabyte/bin/ysqlsh -h yb-tserver-n1 -t -c 'CREATE DATABASE database2;'
          docker exec -i yb-tserver-n1 /home/yugabyte/bin/ysqlsh -h yb-tserver-n1 -t -d database2 < ddl-scripts/create_tables_yugabyte.sql

      - name: test
        run: sbt -Dpekko.persistence.r2dbc.dialect=yugabyte ++${{ matrix.SCALA_VERSION }} test

  test-mysql:
    name: Run tests with MySQL
    runs-on: ubuntu-latest
    strategy:
      matrix:
        SCALA_VERSION: [ 2.13, 3.3 ]
        JAVA_VERSION: [ 17, 21 ]
    if: github.repository == 'apache/pekko-persistence-r2dbc'
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Java ${{ matrix.JAVA_VERSION }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: ${{ matrix.JAVA_VERSION }}

      - name: Install sbt
        uses: sbt/setup-sbt@af116cce31c00823d3903ce687f9cda3a4f19f1b # v1.2.1

      - name: Cache Coursier cache
        uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d # v8.1.1

      - name: Enable jvm-opts
        run: cp .jvmopts-ci .jvmopts

      - name: Start DB
        run: |-
          docker compose -f docker/docker-compose-mysql.yml up -d --wait
          # loop to wait for the DB to be ready
          for i in {1..8}; do
            if docker exec -i docker-mysql-db-1 mysql \
                -h 127.0.0.1 --user=root --password=root --database=mysql -e 'SELECT 1;' 2>/dev/null; then
              break
            fi
            echo "Retry $i: SQL check failed, waiting before retry..."
            sleep $((i * 2))
          done
          docker exec -i docker-mysql-db-1 mysql -h 127.0.0.1 --user=root --password=root --database=mysql < ddl-scripts/create_tables_mysql.sql
          docker exec -i docker-mysql-db-1 mysql -h 127.0.0.1 --user=root --password=root -e 'CREATE SCHEMA database1;'
          docker exec -i docker-mysql-db-1 mysql -h 127.0.0.1 --user=root --password=root --database=database1 < ddl-scripts/create_tables_mysql.sql
          docker exec -i docker-mysql-db-1 mysql -h 127.0.0.1 --user=root --password=root -e 'CREATE SCHEMA database2;'
          docker exec -i docker-mysql-db-1 mysql -h 127.0.0.1 --user=root --password=root --database=database2 < ddl-scripts/create_tables_mysql.sql

      - name: test
        run: sbt -Dpekko.persistence.r2dbc.dialect=mysql ++${{ matrix.SCALA_VERSION }} ${{ matrix.COMPILE_ONLY && 'Test/compile' || 'test' }}

  test-docs:
    name: Docs
    runs-on: ubuntu-latest
    if: github.repository == 'apache/pekko-persistence-r2dbc'
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 17

      - name: Install sbt
        uses: sbt/setup-sbt@af116cce31c00823d3903ce687f9cda3a4f19f1b # v1.2.1

      - name: Cache Coursier cache
        uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d # v8.1.1

      - name: Enable jvm-opts
        run: cp .jvmopts-ci .jvmopts

      - name: Compile docs
        run: |-
          sbt docs/paradox
